---
# yamllint disable rule:line-length
jenkinsx::master:
  master:
    containerEnv:
      - name: CASC_VAULT_PATHS
        value: "${vault_root}/dockerhub,${vault_root}/ghslacker,${vault_root}/github_api,${vault_root}/github_oauth,${vault_root}/scipipe-publish,${vault_root}/slack,${vault_root}/versiondb_ssh"
jenkinsx::casc:
  credentials:
    system:
      domainCredentials:
        - credentials:
            - string:
                id: slack-default-channel
                scope: GLOBAL
                description: Default slack channel
                secret: dmj-jhoblitt-curly
            - string:
                id: slack-channel-prefix
                scope: GLOBAL
                description: Prefix for generated slack channels
                secret: dmjjc
