---
# yamllint disable rule:line-length
lookup_options:
  jenkinsx::casc:
    merge:
      strategy: deep
      merge_hash_arrays: false
      sort_merged_arrays: false
jenkinsx::casc:
  jenkins:
    nodes:
      - permanent: &osx_node
          labelString: 'osx osx-10.13 high_sierra'
          mode: EXCLUSIVE
          name: high_sierra-1
          numExecutors: 1
          remoteFS: /Users/square/j
          launcher:
            sSHLauncher: &osx_ssh
              credentialsId: sqre-osx
              host: mac1.lsst.cloud
              launchTimeoutSeconds: 210
              maxNumRetries: 0
              port: 22
              retryWaitTime: 15
              prefixStartSlaveCmd: "export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin;"
              sshHostKeyVerificationStrategy:
                manuallyTrustedKeyVerificationStrategy:
                  requireInitialManualTrust: true
          nodeProperties:
            - envVars:
                env:
                  - key: 'PATH+LOCAL_BIN'
                    value: /usr/local/bin
      - permanent:
          <<: *osx_node
          name: high_sierra-2
          launcher:
            sSHLauncher:
              <<: *osx_ssh
              host: mac2.lsst.cloud
      - permanent:
          <<: *osx_node
          labelString: 'osx osx-10.14 mojave'
          name: mojave-1
          launcher:
            sSHLauncher:
              <<: *osx_ssh
              host: mac3.lsst.cloud
      - permanent:
          <<: *osx_node
          labelString: 'osx osx-10.14 mojave'
          name: mojave-2
          launcher:
            sSHLauncher:
              <<: *osx_ssh
              host: mac4.lsst.cloud
      - permanent:
          <<: *osx_node
          labelString: 'osx osx-10.14 mojave'
          name: mojave-3
          launcher:
            sSHLauncher:
              <<: *osx_ssh
              host: mac5.lsst.cloud
      - permanent:
          <<: *osx_node
          labelString: 'osx osx-10.14 mojave'
          name: mojave-4
          launcher:
            sSHLauncher:
              <<: *osx_ssh
              host: mac6.lsst.cloud
  credentials:
    system:
      domainCredentials:
        - credentials:
            - string:
                id: slack-default-channel
                scope: GLOBAL
                description: 'Default slack channel'
                secret: dm-jenkins
            - string:
                id: slack-channel-prefix
                scope: GLOBAL
                description: 'Prefix for generated slack channels'
                secret: dmj
            - basicSSHUserPrivateKey:
                id: sqre-osx
                scope: GLOBAL
                description: 'SQRE OSX build agents'
                username: "${osx_ssh_user}"
                privateKeySource:
                  directEntry:
                    privateKey: "${osx_ssh_private_key}"
            - usernamePassword:
                id: aws-cmirror-push
                scope: GLOBAL
                description: push conda packages -> s3
                username: "${cmirror_aws_access_key_id}"
                password: "${cmirror_aws_secret_access_key}"
            - usernamePassword:
                id: github_backup
                scope: GLOBAL
                description: 'github_backup AWS credentials'
                username: "${github_backup_aws_access_key_id}"
                password: "${github_backup_aws_secret_access_key}"
            - usernamePassword:
                id: squash-api-user
                scope: GLOBAL
                description: 'user/pass for Squash API endpoint'
                username: "${squash_api_user}"
                password: "${squash_api_pass}"
            - usernamePassword:
                id: ltd-mason-aws
                scope: GLOBAL
                description: ltd-mason
                username: "${ltd_mason_aws_access_key_id}"
                password: "${ltd_mason_aws_secret_access_key}"
            - usernamePassword:
                id: ltd-keeper
                scope: GLOBAL
                description: ltd-keeper
                username: "${ltd_keeper_user}"
                password: "${ltd_keeper_pass}"
jenkinsx::master:
  master:
    containerEnv:
      - name: CASC_VAULT_PATHS
        value: "${vault_root}/scipipe-publish,${vault_root}/slack,${vault_root}/ghslacker,${vault_root}/github_oauth,${vault_root}/github_api,${vault_root}/dockerhub,${vault_root}/versiondb_ssh,XXXTESTXXX"
